### ISSUE TITLE
Fix Form Buttons

### ISSUE THREAD

**Issue by jaygabe** [O1SoftwareNetwork/repairs#13]
The Back form button should not be present when the form is in state 0. The Next form button should convert to a server action that processes the form when the form is in state 2. It should also change from "Next" to "Submit" or "Confirm" in state 2. Please see AppointmentFormState in the ServicableSignup component:

```
enum AppointmentFormState {
    DIAGNOSIS,
    SCHEDULE,
    CONTACT
}
```

**Comment by RaspBri** [comment]
My Pull Request for this issue https://github.com/O1SoftwareNetwork/repairs/pull/14

Was unsure about what server to connect the submit button to, so that is still a pending task.
